---
- name: Run Tasks on all servers
  hosts: all

  tasks:
    - name: Apt update
      apt:
        update_cache: yes
        upgrade: yes
    - name: install python3-pip-python3-pip
      package:
        name:
          - python3
          - python3-pip
          - pip
    - name: Install Locust
      shell: |
        pip install locust --break-system-packages
    - name: Create Locust folder
      file:
             path: /root/locust
             state: directory
             mode: '0755'
      become: yes
    - name: Copy locustfile.py from local to server
      copy:
        src: locust/locustfile.py
        dest: /root/locust/
- name: Run Tasks on Master Servers
  hosts: master

  tasks:
    - name: Run locust on Master
      shell: |
        nohup locust -f /root/locust/locustfile.py --master --host=http://www.mir.de --web-port=8089 > locust_master.log 2>&1 &

- name: Run Locust on Worker
  hosts: worker1, worker2

  tasks:
    - name: Fetch Master IP
      set_fact:
        master_private_ip: "{{ hostvars['master']['private_networks'][0]['ip'] }}"
    - name: Run Locust on Worker
      shell: nohup locust -f /root/locust/locustfile.py --worker --master-host={{ master_private_ip }} --host=http://www.mir.de --web-port=8089 > locust_worker.log 2>&1 &
